name: homemarket
description: A MARKET FOR PROPERTIES AND SERVICES

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  google_sign_in: ^4.5.6
  firebase_storage: ^5.2.0
  image_picker: ^0.6.7+17
  url_launcher: ^5.6.0
  flutter_automation: ^1.4.0
  devicelocale: ^0.3.3
  intl_phone_number_input: ^0.6.0
  intl_phone_field: ^1.4.2
  from_css_color: ^1.1.0
  shimmer: ^1.1.2
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1


flutter_icons:
  android: "launcher_icon"
  image_path: "images/launcher_logo.png"

  ios: true

flutter_launcher_name:
  name: "Home Market"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - images/
  - assets/